### ISSUE TITLE
Multiple Subscribers with Same Topic Name Are Ignored

### ISSUE THREAD

**Issue by JWhitleyWork** [upowerrobotics/ros2_fabric#10]
The following YAML sequence exposes a bug:

```
    subscribers:
      - name: detected_objects
        node: node1
      - name: detected_objects
        node: node2
```

In this case, only the last subscriber in the list will be created.
