### ISSUE TITLE
Nodes with root_node=False and terminal_node=False Require Both Publishers and Subscribers

### ISSUE THREAD

**Issue by JWhitleyWork** [upowerrobotics/ros2_fabric#12]
This rule is not being accounted for in the current logic in `config2nodes.py`. The following node configuration is currently valid and should not be:

```
      - name: node_name
        root_node: false
        terminal_node: false
        publishers:
          - name: topic_name
            msg_size: 800K
            frequency: 10.0
```
